services:
  api:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: e-commercial-api

    restart: unless-stopped

    ports:
      - '3000:3000'

    env_file:
      - .env

    depends_on:
      - mysql
      - redis

    volumes:
      - .:/app
      - /app/node_modules

    command: sh -c "pnpm run migration:run && pnpm run start:dev"

  mysql:
    image: mysql:8.4

    container_name: e-commercial-mysql

    restart: unless-stopped

    environment:
      MYSQL_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MYSQL_DATABASE: ${DATABASE_NAME}

    ports:
      - '3307:3306'

    volumes:
      - mysql_data:/var/lib/mysql

  redis:
    image: redis:7-alpine

    container_name: e-commercial-redis

    restart: unless-stopped

    ports:
      - '6379:6379'

    volumes:
      - redis_data:/data

volumes:
  mysql_data:
  redis_data:
