name: E-Commerce CI

on:
  push:
  pull_request:

jobs:
  ci:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.4
        env:
          MYSQL_ROOT_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          MYSQL_DATABASE: ${{ vars.DATABASE_NAME }}
        ports:
          - 3307:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -uroot -p${MYSQL_ROOT_PASSWORD}"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=10

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 12.5.1

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: 24
          cache: pnpm
          cache-dependency-path: pnpm-lock.yaml

      - name: Check versions
        run: |
          node --version
          pnpm --version

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run database migrations
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          DATABASE_HOST: ${{ vars.DATABASE_HOST}}
          DATABASE_PORT: ${{ vars.DATABASE_PORT}}
          DATABASE_USERNAME: ${{ vars.DATABASE_USERNAME }}
          DATABASE_PASSWORD: ${{ secrets.DATABASE_PASSWORD }}
          DATABASE_NAME: ${{ vars.DATABASE_NAME }}
        run: pnpm run migration:run

      - name: Build
        env:
          NODE_ENV: ${{ vars.NODE_ENV }}
          PORT: ${{ vars.PORT }}
          REDIS_URL: ${{ vars.REDIS_URL }}
        run: pnpm build

  docker:
    needs: ci

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and Push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/the-bozorg/e-commercial:latest
